<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DiagramGlobalToolService" nsURI="http://DiagramGlobalToolService/1.0"
    nsPrefix="DiagramGlobalToolService">
  <eClassifiers xsi:type="ecore:EClass" name="DiagramGlobalToolDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="DiagramDefinitionRef" upperBound="-1"
        eType="#//DiagramDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagramDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="DrawerDefinitionRef" upperBound="-1"
        eType="#//DrawerDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DiagramType" lowerBound="1"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DrawerDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="AbstractToolRef" upperBound="-1"
        eType="#//AbstractTool" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTool" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isEdge" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tool" eSuperTypes="#//AbstractTool">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementTypes" upperBound="-1"
        eType="#//ElementType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ElementType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementType" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToolMetaModel" eSuperTypes="#//AbstractTool">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaModel" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
